# Generated by Django 4.2.2 on 2023-12-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='department',
            new_name='department_id',
        ),
    ]
