# Generated by Django 4.2.2 on 2023-12-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_course_department'),
        ('sign', '0003_rename_department_id_course_department'),
    ]

    operations = [
    ]
